version: '3'

services:
  main:
    volumes:
      - ./:/code
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-u", "/code/process_html.py"]
    #command: ["python", "-u", "navigator.py"]